/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package S4;

/**
 *
 * @author juanp
 */
public class Servicios extends javax.swing.JFrame {

    /**
     * Creates new form Servicios
     */
    public Servicios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        BG = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        totalLuzTxt = new javax.swing.JTextField();
        totalAguaTxt = new javax.swing.JTextField();
        triRdBtn = new javax.swing.JRadioButton();
        monoRdBtn = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        consumoMetrosCub = new javax.swing.JTextField();
        consumoKW = new javax.swing.JTextField();
        borrarBtn = new javax.swing.JButton();
        aceptarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        BG.setBackground(new java.awt.Color(153, 153, 153));
        BG.setMinimumSize(new java.awt.Dimension(800, 600));
        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setText("Agua");
        BG.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Calcular Pago de Servicios Basicos");
        BG.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel3.setText("Consumo m³:");
        BG.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 200, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel4.setText("Total:");
        BG.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel5.setText("Tipo:");
        BG.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel6.setText("Consumo KW:");
        BG.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 200, -1));

        totalLuzTxt.setEditable(false);
        totalLuzTxt.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        totalLuzTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalLuzTxtActionPerformed(evt);
            }
        });
        BG.add(totalLuzTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 160, -1));

        totalAguaTxt.setEditable(false);
        totalAguaTxt.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        totalAguaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalAguaTxtActionPerformed(evt);
            }
        });
        BG.add(totalAguaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 410, 160, -1));

        triRdBtn.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroup1.add(triRdBtn);
        triRdBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        triRdBtn.setText("Trifasico");
        BG.add(triRdBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, -1));

        monoRdBtn.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroup1.add(monoRdBtn);
        monoRdBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        monoRdBtn.setText("Monofasico");
        BG.add(monoRdBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel7.setText("Luz");
        BG.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel8.setText("Cargo fijo:");
        BG.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel9.setText("Total:");
        BG.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel10.setText("Cargo fijo:");
        BG.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        jLabel11.setText("S/2.50");
        BG.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        jLabel12.setText("S/3.30");
        BG.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, -1, -1));

        consumoMetrosCub.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        consumoMetrosCub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consumoMetrosCubActionPerformed(evt);
            }
        });
        BG.add(consumoMetrosCub, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 210, 90, -1));

        consumoKW.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        consumoKW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consumoKWActionPerformed(evt);
            }
        });
        BG.add(consumoKW, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 90, -1));

        borrarBtn.setBackground(new java.awt.Color(255, 51, 51));
        borrarBtn.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        borrarBtn.setText("Borrar");
        borrarBtn.setToolTipText("");
        borrarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        borrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarBtnActionPerformed(evt);
            }
        });
        BG.add(borrarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 510, -1, -1));

        aceptarBtn.setBackground(new java.awt.Color(0, 204, 0));
        aceptarBtn.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        aceptarBtn.setText("Aceptar");
        aceptarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aceptarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarBtnActionPerformed(evt);
            }
        });
        BG.add(aceptarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void totalLuzTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalLuzTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalLuzTxtActionPerformed

    private void totalAguaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalAguaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalAguaTxtActionPerformed

    private void consumoMetrosCubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consumoMetrosCubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consumoMetrosCubActionPerformed

    private void consumoKWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consumoKWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consumoKWActionPerformed

    private void aceptarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarBtnActionPerformed
        // TODO add your handling code here:
        boolean esTrifasico = false;
        double KW = Double.parseDouble(consumoKW.getText());
        if (monoRdBtn.isSelected()){
            esTrifasico = false;
        }else{
            esTrifasico = true;
        }
        Luz luz = new Luz(3.3, esTrifasico, KW);
        
        double consumoMetrosCubicos = Double.parseDouble(consumoMetrosCub.getText());
        Agua agua = new Agua(consumoMetrosCubicos, 2.5);
        
        luz.calcularMontoFinal();
        agua.calcularMontoFinal();
        
        totalLuzTxt.setText("S/ "+String.valueOf(luz.montoFinal));
        totalAguaTxt.setText("S/ "+String.valueOf(agua.montoFinal));
        
    }//GEN-LAST:event_aceptarBtnActionPerformed

    private void borrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarBtnActionPerformed
        // TODO add your handling code here:
        consumoKW.setText(null);
        consumoMetrosCub.setText(null);
        totalLuzTxt.setText(null);
        totalAguaTxt.setText(null);
        
    }//GEN-LAST:event_borrarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Servicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Servicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Servicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Servicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Servicios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JButton aceptarBtn;
    private javax.swing.JButton borrarBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField consumoKW;
    private javax.swing.JTextField consumoMetrosCub;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton monoRdBtn;
    private javax.swing.JTextField totalAguaTxt;
    private javax.swing.JTextField totalLuzTxt;
    private javax.swing.JRadioButton triRdBtn;
    // End of variables declaration//GEN-END:variables
}
